### ISSUE TITLE
您好 请问一下 我在node.js里按照菱形用path画自定义的图形 bg锚点位置不对

### ISSUE THREAD

**Issue by yuxinmei** [keydone/g6-graph#25]
<img width="182" alt="image" src="https://user-images.githubusercontent.com/44768546/129308054-d731a8d9-2a88-4b38-b875-1219bf10d352.png">
就如上图

**Comment by claudewowo** [comment]
bg在添加时也要指定x,y

**Comment by yuxinmei** [comment]
搜噶谢谢 我试试哈
然后还有一个问题就是我只修改了data.js 想画一个简单的流程图
但是只有一瞬间位置正确 然后立马就变成左上角了
<img width="463" alt="image" src="https://user-images.githubusercontent.com/44768546/129310236-35215b14-170b-4c00-bfbd-aff35eef7167.png">

**Comment by yuxinmei** [comment]
🙇‍♀️
这个bg的x y 我能参考哪里的写呀  我没自己添加 是默认的

**Comment by claudewowo** [comment]
默认绘制坐标是左上角开始, 可以试试 fitCenter

**Comment by claudewowo** [comment]
> 🙇‍♀️
> 这个bg的x y 我能参考哪里的写呀 我没自己添加 是默认的

改了菱形坐标就要绘制完成后查找锚点中的元素 findById => getChildren => getbg, 然后给元素重新设置坐标 bg.attr({x, y})
基础不扎实可以看看我的bilibili视频教程

**Comment by yuxinmei** [comment]
> 默认绘制坐标是左上角开始, 可以试试 fitCenter

谢谢这个好用啦 用的fitView！ 感谢您！🙏

**Comment by yuxinmei** [comment]
> findById => getChildren => getbg

收到！谢谢！！ 辛苦啦！笔芯♥️
