### ISSUE TITLE
新增连接线时候的问题

### ISSUE THREAD

**Issue by weiCheng24** [keydone/g6-graph#29]
步骤：
1：拖拽一个新节点，点击 锚点 添加连接线，（随意晃动别连接到其他节点）。
2：再拖拽一个新节点，点击 锚点 连接线。
![1634631786(1)](https://user-images.githubusercontent.com/88021076/137872856-f3f70bd3-9e98-4b90-ac29-f830e49d0f4c.jpg)
![1634631777(1)](https://user-images.githubusercontent.com/88021076/137872878-294574a9-67ea-475b-be6f-ecf27a0c2f8d.jpg)

**Comment by claudewowo** [comment]
该线目前的设计是必须要连接到其他节点,
否则应在鼠标释放时移除刚刚添加的线,
建议在鼠标释放后监听释放目标是否为锚点,
如果是非锚点就移除线.

感谢反馈, 该功能后续迭代时会加上, 时间待定,
如果急需使用建议先自己处理.

**Comment by weiCheng24** [comment]
谢谢你的回复。鼠标释放后的监听（那我新增一个监听事件）
释放目标是否为锚点。
另外，就算正常连接线，也会出现这种蓝色多余线的问题。
![1634633894(1)](https://user-images.githubusercontent.com/88021076/137877779-5b6ec47d-97fd-4a78-9038-3cddc9aec648.jpg)

**Comment by claudewowo** [comment]
有个问题就是当鼠标移入到画布以外的区域时(包括画布外和比画布层级高的div)会阻断画线, 所以需要在鼠标按下时隐藏诸如 tooltip等内容, 这个逻辑需要自己按需编写, 只要没有断开画线就不会出现多余的部分

**Comment by weiCheng24** [comment]
好的，谢谢你的回复
