### ISSUE TITLE
节点的宽高改变

### ISSUE THREAD

**Issue by jiazhigang727** [keydone/g6-graph#33]
节点的宽高改变以后，锚点的位置错位了吗？有解决办法吗

**Comment by claudewowo** [comment]
大概思路:

node.update({
  width: xx,
  height:xx,
});

const group = node.getContainer();
const anchors = group.anchorShapes();

anchors.forEach(p => {
  p.update({
    x: xx,
    y: xx,
  })
});

**Comment by jiazhigang727** [comment]
谢谢，研究研究
