### ISSUE TITLE
diamond-node 节点使用 updateItem 方法更新大小时无效

### ISSUE THREAD

**Issue by davy-gan** [keydone/g6-graph#38]
// 所有节点默认配置
        defaultNode: {
          type: 'rect-node',
          style: {
            radius: 10,
            width: 100,
            height: 50,
            cursor: 'move',
            fill: '#ecf3ff',
            stroke: '#40a9ff',
            r: 40,
            rx: 50,
            ry: 25,
            size: [100, 50], //在这里改变默认值大小的时候菱形可以改变大小
          },
          labelCfg: {
            fontSize: 20,
            style: {
              cursor: 'move',
              fill: '#040c2c'
            },
          },
        },

const model = e.item.get('model');
          this.config = model;
          this.label = model.label;
          console.log(model, 'model')
          this.labelCfg = {
            fontSize: model.labelCfg.fontSize,
            style: {
              fill: model.labelCfg.style.fill,
            },
          };
          this.node = {
            style: {
              fill: model.style.fill,
              stroke: model.style.stroke,
              lineDash: model.style.lineDash || 'none',
              width: model.style.width,
              height: model.style.height,
              r: model.style.r,
              rx: model.style.rx,
              ry: model.style.ry,
              size: model.style.size,
            },
            shape: model.type,
          };

node: {
        style: {
          fill: '',
          lineDash: 'none',
          stroke: '',
          width: 160,
          height: 60,
          r: 40,
          rx: 50,
          ry: 25,
          size: [100, 50],
        },
        shape: 'rect-node',
 },

<template v-if="node.shape==='diamond-node'">
          <div class="config-item">
            宽:
            <a-input-number v-model="node.style.size[0]" />px
          </div>
          <div class="config-item">
            高:
            <a-input-number v-model="node.style.size[1]" />px
          </div>
        </template>

save () {
      // eslint-disable-next-line no-alert
      const item = this.graph.findById(this.config.id)
      console.log(item, {
        ...this.node,
        label: this.label,
        labelCfg: this.labelCfg
      })
      this.graph.updateItem(item, {
        id: this.config.id,
        ...this.node, //此处更新大小 圆 椭圆 方形 都正常 菱形无效
        // type: this.node.shape,
        label: this.label,
        labelCfg: this.labelCfg
      })
      // item.update({
      //   // ...this.node,
      //   label: this.label,
      //   // labelCfg: this.labelCfg
      // })
    },
使用的就是demo上的例子 加了一个设置菱形大小

**Comment by claudewowo** [comment]
已处理, 可以通过 size 改变节点大小
另外有锚点和边更新需要自行更新相应属性和坐标
