### ISSUE TITLE
和 react-flow 相比，各有什么优缺点呢？

### ISSUE THREAD

**Issue by zxhycxq** [keydone/g6-graph#41]
看到大佬的视频非常优秀，不知道可否了解过 react-flow ？和阿里 antv 旗下的 g6/x6 相比，各有什么优缺点呢？

**Comment by keman5** [comment]
react-flow 是单独为react服务的, 而这个框架是无关框架, 无论是你用HTML, vue, react, 还是任何js框架, 都能通过canvas直接绘制流程图, 或者编排可视化任务, 而且非常灵活, 可以绘制专业布局, 自由度超高, 中文文档, 国内普遍在用antv系列
