### ISSUE TITLE
关于自定义mode疑问

### ISSUE THREAD

**Issue by qhj49413** [keydone/g6-graph#9]
自定义mode： drag-node 其中我看源码enableDelegate属性并没有设置为true，但是拖动节点过程中为何还是方框代替元素的直接移动

**Comment by claudewowo** [comment]
0.6版本以前是与官方内置行为重名, 相对于进行了覆盖, 0.6.0 开始设置了新的行为名称 drag-shadow-node, 与官方内置行为进行了区分, 具体用法可以参照使用教程
